### ISSUE TITLE
Ediff faces work poorly with dark theme

### ISSUE THREAD

**Issue by benkuhn** [bbatsov/solarized-emacs#134]
Using ediff with the `solarized-dark` theme, the backgrounds of diff regions can get quite bright. Combined with dark text (e.g. comments) superimposed, this can make some text very hard to read:

![screen shot 2014-11-07 at 2 03 16 pm](https://cloud.githubusercontent.com/assets/304831/4961027/f5bd6dc8-66c9-11e4-8659-d0c838f4cda5.png)

Here it is with the light theme for comparison:
![screen shot 2014-11-07 at 2 06 12 pm](https://cloud.githubusercontent.com/assets/304831/4961058/595ff9b8-66ca-11e4-8728-a04fcc55e345.png)

**Comment by thomasf** [comment]
I think that these colors need to be calculated at theme creation time to allow the various levels of highlight to work properly.

**Comment by wyuenho** [comment]
This can be closed now right?

**Comment by terzievk** [comment]
I really like the solarized theme. However I have a problem with ediff too - mainly with how translucent the marking is, which results in unreadable comments. Here is a screenshot:

![screenshot from 2018-09-26 00-18-56](https://user-images.githubusercontent.com/17403291/46044155-a5d44180-c122-11e8-8722-88dc7b040174.png)
So my question is: Is there a way to set a default go to theme to be set for such problematic occasions?

P.S: I don't know if this is mentioned elsewhere but after loading another theme and then loading the solarized theme back it sort of fixed itself *weird*. I don't think this sounds clear enough so here are some screenshots:
- here the solarized theme is set by default:

![screenshot from 2018-09-26 00-18-56](https://user-images.githubusercontent.com/17403291/46044369-40348500-c123-11e8-8d1f-e233796d1614.png)

- here I load the deeper-blue theme:

![screenshot from 2018-09-26 00-19-12](https://user-images.githubusercontent.com/17403291/46044461-7a9e2200-c123-11e8-8c12-209842ca81c5.png)

- now the marking is opaque and easily readable:

![screenshot from 2018-09-26 00-19-15](https://user-images.githubusercontent.com/17403291/46044483-8d185b80-c123-11e8-863b-515050511d72.png)

- now I load the solarized-dark theme:

![screenshot from 2018-09-26 00-19-28](https://user-images.githubusercontent.com/17403291/46044509-9acde100-c123-11e8-95c4-da8cec525ca2.png)

- the result is sort of mix between the two:

![screenshot from 2018-09-26 00-19-35](https://user-images.githubusercontent.com/17403291/46044529-b0430b00-c123-11e8-974e-ba470d2445db.png)
...and in each consecutive call of ediff the marking stays the same as in the last picture until emacs is closed. It might not be the best combination color wise, yet it gets the job done. 

- and it doesn't seem to affect the colors after exiting ediff. Here is a screenshot after exiting ediff:

![screenshot from 2018-09-26 00-41-00](https://user-images.githubusercontent.com/17403291/46045016-18462100-c125-11e8-9665-021ea1f059d4.png)

- and here is a screenshot after reopening emacs, when the "merge" between the two themes is reset and the ediff would look just as in the first picture:

![screenshot from 2018-09-26 00-41-35](https://user-images.githubusercontent.com/17403291/46045088-47f52900-c125-11e8-8552-26c5f36b6c98.png)

I guess my second question is: Is there a way to make use of this "themes merge" and do you think that it is a good idea to make a function to change the theme to deeper-blue and back to solarized-dark after loading emacs in order to replicate the effect each time?

**Comment by wyuenho** [comment]
See https://github.com/bbatsov/solarized-emacs/issues/194#issuecomment-398796759
