### ISSUE TITLE
Unreadable text on active high contrast powerline

### ISSUE THREAD

**Issue by aport** [bbatsov/solarized-emacs#175]
Commit https://github.com/bbatsov/solarized-emacs/commit/f09e055274ed97db5903f1b467c6e07074d1d0dc introduced text readibility issues on active high-contrast powerline. Text using solarized green (and possibly yellow/orange) are extremely difficult to read.

There is a short discussion and image provided on the commit above.

@ryanartecona is looking into this.

**Comment by ryanartecona** [comment]
Ok, I've looked into this a bit.

![this screenshot](https://cloud.githubusercontent.com/assets/66264/6977007/bc81e568-d968-11e4-96bf-5b7eb131406b.png)
As in this screenshot, the solarized green is completely illegible on the active high-contrast modeline. Other colors aren't quite as bad (legible if you squint a bit), but none of them work very well there. The high-contrast modeline background works okay with the default foreground, but not much else.

This was a little surprising to me, since I knew one of the basic facts of solarized is the various highlight colors were supposed to be equally balanced on both the light and dark backgrounds.

I think the problem stems from how the high-contrast modeline inverses colors. It inverses the *current* theme's text and background color (text color becomes background and vice versa), instead of using the *opposite* theme's default text and background color (solarized-light would use solarized-dark colors in its high-contrast modeline, and vice versa).

For the problem in this issue, I tried using the darker/lighter variants of colors (`green-hc`, etc.), but that doesn't really work. If I change the `green` in the screenshot to be lighter (`green-lc`), it becomes slightly more legible in the *active* modeline, but less legible in the *inactive* modeline. This is because there's only one `compilation-mode-line-exit` face; I can't give it a different color for the active/inactive modeline.

There are a couple viable solutions to this problem:
  1. Use high-contrast foreground and low-contrast background for all colored mode-line faces, as in the red in these screenshot.
  ![screen shot 2015-04-04 at 6 47 18 pm](https://cloud.githubusercontent.com/assets/889991/6994999/12f4e024-dafb-11e4-97ca-f8633331dc79.png)
  ![screen shot 2015-04-04 at 6 47 54 pm](https://cloud.githubusercontent.com/assets/889991/6995002/265e35de-dafb-11e4-9677-89bb1a37ec0e.png)

  This would be a way for colors to work with both the active high-contrast and inactive normal modelines.  The high-contrast modeline background could stay as-is. Some colors could be given this treatment, and maybe some colors we could downgrade to use the default modeline text color there.

  2. Change the high-contrast modeline background to use the opposite theme's background, instead of the current theme's text color. That would look something like the below screenshot.
  ![screen shot 2015-04-04 at 7 32 29 pm](https://cloud.githubusercontent.com/assets/889991/6995109/88f5cd28-db01-11e4-94ae-1a9ea8d61913.png)

  This would make the high-contrast modeline *a lot* higher contrast than it already is. The advantage would be colors would work just fine in it, but I think this is probably *too* high contrast. 

I'm in favor of (1). I can make the important colors stand out, and make the rest just use the normal modeline text color, perhaps bolding some.

**Comment by thomasf** [comment]
@ryanartecona  The overall solarized color balance is tweaked for perceived  lightness, other properties might vary. For general semantics it's not all that bad that some accent colors stand out more than other, the largest downside I can th . The fact that green is very soft

**Comment by thomasf** [comment]
If possible the lc/hc colors should be left out of the mode line.. They call for too much attention.. 

 I've spent an insane amount of hours experimenting with the  mode/header line related  faces before to get it where it is now, it's very tricky because of the very limited palette and edge cases like this.

Seems hard to sovle this one properly using only the theme system.
Maybe some non theme elisp code could be used to assist this?  
For a very long time I've been meaning to create a solarized-config.el package which has additional  look'n'feel realted code and configuration for various modes from my init.el..

**Comment by ryanartecona** [comment]
@thomasf After sleeping on it and after your comments, I completely agree. I think the normal and high-contrast modelines work about as well as they can given the palette. It's annoying that colors don't work as well as they do on the normal theme backgrounds, but there doesn't seem to be a clean fix.

I'd be happy to help on a non-theme elisp solution, but my elisp skills are not very strong yet. I've only been about 1 month on Emacs.

Re a solarized-config.el: would that be a separate package, or live here? And would it be a collection of tweaks to make things work better with solarized, or more utilities for someone to make those kinds of tweaks themselves? I'm also a bit confused on how that would relate to this issue.

**Comment by thomasf** [comment]
If the green one is the problem I think setting compilation-mode-line-exit to something like `:foreground unspecified :weight bold ` should work. I have no time to test it myself right now.

The solarized-config.el would be placed in this repo regardless if it would be installed as a separate package or not. I just hinted about my thoughts on that since that probably would  be the place to put additional code.

**Comment by aport** [comment]
I actually prefer the absense of colors in the modeline. Using foreground unspecified looks excellent. Besides, the buffer contents itself will show red text if the compilation failed, so I don't see the need to duplicate this color on the modeline.

Making this configurable (no colored faces on modeline) would be a good compromise IMO.

**Comment by thomasf** [comment]
It's changed now.. I did exactly the same thing for the smart mode line mode line a week ago or so.

**Comment by thomasf** [comment]
Question: Does removing the green exit status color resolve this issue?
I'm having some trouble keeping track of what is what for all trecent mode line related issues which also involves 2 different mode line packages 

reen enough or is the red too much of a problem as well?
I will probably always stand on the side of those who wants to remove colors so I'm maybe more biased than other people..

**Comment by aport** [comment]
I'm happy with the change and I'll close the ticket. Thanks!
