### ISSUE TITLE
magit-blame headers hard to read

### ISSUE THREAD

**Issue by emil-e** [bbatsov/solarized-emacs#195]
The orange and the gray colors are very hard to read for me. Any ideas to what these should be changed? It didn't use to look like that before magit 2.1.

![screen shot 2015-07-15 at 09 36 51](https://cloud.githubusercontent.com/assets/5737870/8693151/2a536b44-2ad5-11e5-8be7-54e587885955.png)

**Comment by thomasf** [comment]
Oh, that looks strange

**Comment by emil-e** [comment]
I would have made a pull request but I'm not familiar with the "style guidelines" so it wasn't obvious to me what the appropriate colors are.

**Comment by thomasf** [comment]
I have written a quick draft with the most important guide lines here https://github.com/bbatsov/solarized-emacs/blob/master/DEV-GUIDE.md

**Comment by wbolster** [comment]
this issue annoys me too: i cannot read the blame headers in dark mode.

would the maintainers accept a pull-request that changes the magit blame headers to this:

![image](https://cloud.githubusercontent.com/assets/748944/13477421/8aebc412-e0cc-11e5-838e-b8023b741447.png)

![image](https://cloud.githubusercontent.com/assets/748944/13477432/97b3c9f6-e0cc-11e5-96f2-591cb7b857af.png)

if so i can make a pr that implements this.

**Comment by emil-e** [comment]
Sure they would since what you're showing is objectively better :)

**Comment by wbolster** [comment]
ok will make a pr.

design rationale: i used yellow(ish) on a secondary background colour because it has a subtle contrast with the surrounding code while still showing clear separators since most syntax colouring for programming languages don't use long yellow(ish) pieces of text.

**Comment by thomasf** [comment]
I would probably at least try to get rid of all accent colors.. I'ts kind of a strange selection of colors as it is now, I wonder if it's just an overlooked part of the theme or if the reason is collision with something else?

**Comment by thomasf** [comment]
I've looked at it briefly and it's a bit complicated to choose good colors since magit-blame exists among already highlighted code it has to not use the normal accent colors like yellow since that..

I came up with this, not really satisfied with it either:

![image](https://cloud.githubusercontent.com/assets/330847/13478536/bda87bca-e0d1-11e5-94a8-d5e0101c3f30.png)

```el
     `(magit-blame-heading ((t (:background ,base03 :foreground ,base01 :underline t))))
     `(magit-blame-hash    ((t (:background ,base03 :foreground ,base01 :underline t))))
     `(magit-blame-name    ((t (:background ,base03 :foreground ,base01 :underline t))))
     `(magit-blame-date    ((t (:background ,base03 :foreground ,base01 :weight bold :underline t))))
     `(magit-blame-summary ((t (:background ,base03 :foreground ,base01 :underline t))))
```

**Comment by wbolster** [comment]
my rationale above was not clear? note that these styles are used to temporarily have some interspersed lines between regular syntax highlighted code. these lines need a subtle but clear contrast with the rest. i tried without any accents but that makes it really hard to see the headers. note that magit blame mode is intended as a temporary history overlay (and can even be toggled by typing 't') so a highlight colour makes sense here.

**Comment by emil-e** [comment]
I think some sort of background color is a good thing, it makes it totally clear that those are headers and not normal code since normal code does not use background colors.

**Comment by thomasf** [comment]
Yeah, it's more ok to use the accents for magit-blame.. The contrasting feature of yellow is mode dependent though..
In prog modes yellow (usually) is the type face so for all langues which has declarations with the type on the left side (C is one) it could become hard to read the screen in some situations.. 

I think I'll take a pull req with your suggestion to begin with at least. You should probably change the message text fg to base1 if its on base02.

**Comment by wbolster** [comment]
to be honest, your screenshot looks completely unusable to me, @thomasf.

bold fonts (i completely disabled these in both gui and terminal), underline (yuck), and no contrast at all, neither in foreground nor background.

magit blame is for temporary excursions into history, not for permanent view. some highlights are in order here imo.

about the yellow: this colour is not prominent in code, so it makes the header stand out while still fitting the theme...

**Comment by wbolster** [comment]
our comments crossed mid air. ☺

didn't try with type declarations. other suggestions? green and blue both looked far less elegant, orange and red way too aggressive.

**Comment by thomasf** [comment]
we could go with yellow,... violet is another option, hardly used at all so it will definitely stand out.

**Comment by wbolster** [comment]
in any case, we're getting somewhere. yay. toggling to light mode every time I blame a file was getting tiresome...

**Comment by thomasf** [comment]
Yeah, I usually use `vc-annotate` to look at these things so I just didn't notice magit-blame at all.

**Comment by wbolster** [comment]
i experimented a tiny bit, and you're right that using yellow is not so nice for languages like C and C++ (because of the type declarations). also, violet looks very out of place (and very ugly) here.

in the end having no colours at all, and using a comment foreground with a subtly highlighted background (secondary content) looks the cleanest to me. after all, the headers _are_ secondary content, basically providing some comments about the code below it. the normal use case of magit blame is that you use it for some exploration: if you want details about a change, you hit enter anyway to show the full commit message + diff.

![image](https://cloud.githubusercontent.com/assets/748944/13490811/de5c3caa-e12e-11e5-8968-af1e1edfc8f6.png)

![image](https://cloud.githubusercontent.com/assets/748944/13490815/e7542d4a-e12e-11e5-920a-a84bbc53b137.png)

not that using the comment colour for the foreground is really needed imo, anything brighter distracts too much from the main content, which should have the primary focus.

**Comment by thomasf** [comment]
The fonts in your screenshots looks like a very heavy weight, is that maybe why you don't like bold? My bold almost feels like your non bold, you should maybe investigate your font settings to get a better balance between bold and regular in Emacs, maybe even try another font?

The reason for this comment is that base01 on base02 looks really pale without bold, remember it's a combination which is quite hard to read if the regular weight is a bit more regular.

**Comment by wbolster** [comment]
the font is just menlo (osx default). on smaller scales it is more crisp:

![image](https://cloud.githubusercontent.com/assets/748944/13507473/ff0864ac-e182-11e5-852b-a9767b8e3aba.png)

**Comment by wbolster** [comment]
also, ensure you view my screenshot at 100% scaling; github scales images in comments i think.

**Comment by thomasf** [comment]
Ah, osx and apples font smoothing algorithm (?) is probably the cause, or maybe the combination of osx and emacs, idk.   I just quickly compared Meslo LG-M and it looks about twice as bold in osx than on my linux desktop.. 

anyway...

![image](https://cloud.githubusercontent.com/assets/330847/13510102/5b307ed4-e18f-11e5-94a3-28a755c5c088.png)

```el
    `(magit-blame-heading ((t (:background ,base02 :foreground ,base0))))
     `(magit-blame-hash    ((t (:background ,base02 :foreground ,base0))))
     `(magit-blame-name    ((t (:background ,base02 :foreground ,base0))))
     `(magit-blame-date    ((t (:background ,base02 :foreground ,base01))))
     `(magit-blame-summary ((t (:background ,base02 :foreground ,base1))))
```

**Comment by thomasf** [comment]
Maybe adding a small amout padding?

![image](https://cloud.githubusercontent.com/assets/330847/13525315/8065ac3a-e200-11e5-8ab3-17f02bcadaee.png)

![image](https://cloud.githubusercontent.com/assets/330847/13525327/8f978d40-e200-11e5-999b-dc5b2480826a.png)

![image](https://cloud.githubusercontent.com/assets/330847/13525348/b78a9a90-e200-11e5-862a-050f19e86f69.png)




```el
`(magit-blame-heading ((t (:background ,base02 :foreground ,base0 :box (:color ,base02 :line-width 2)))))
`(magit-blame-hash    ((t (:background ,base02 :foreground ,base0 :box (:color ,base02 :line-width 2)))))
`(magit-blame-name    ((t (:background ,base02 :foreground ,base1 :box (:color ,base02 :line-width 2)))))
`(magit-blame-date    ((t (:background ,base02 :foreground ,base1 :box (:color ,base02 :line-width 2)))))
`(magit-blame-summary ((t (:background ,base02 :foreground ,base0 (:color ,base02 :line-width 2)))))
```

**Comment by emil-e** [comment]
I think all of these look much better than what we have now. I slightly prefer it without padding since it makes it a bit more compact but I don't mind it either.

**Comment by thomasf** [comment]
if @tarsius  does not have anything to say I'll start by adding the version in the last screenshot so we at least have something thats somewhat agreeable for now.

**Comment by tarsius** [comment]
Ah yes. I have some mixed feelings about this. This certainly looks better, but at the same time I think the headers are now too similar to regular text.

The background color is good, but I would change the text somehow. It might be worth trying to make the text color darker (or lighter?) and/or to make it bold (or italic?).
 
Speaking of italic, it appears from the last screen-shot that the slant has to be enforced explicitly - most blame headers are regular but a few are italic, probably because they somehow inherited that from the surrounding text.

**Comment by thomasf** [comment]
The almost never used violet could possibly become useful here then.. I have excluded using it normally for rare corner cases such as this.

![image](https://cloud.githubusercontent.com/assets/330847/13708632/fe495480-e7af-11e5-980f-78f7e6413e64.png)

This is a particularly hard situation to theme (using solarized) since its very easy to do too little or too much.

**Comment by thomasf** [comment]
And, yeah, the italic should probably be specified properly.

**Comment by thomasf** [comment]
An idea is to maybe introduce a blame line prefix with it's own color in magit so that a clearly colored  • or something can be used to identify lines coming from magit-blame?

**Comment by oscarfv** [comment]
I'm not against finding the perfect solution, but in the meantime having any of the proposals that allow to use the feature would be a huge improvement.

**Comment by tarsius** [comment]
> I'm not against finding the perfect solution,

Nor am I. But since I am trying to take a break working on this isn't a high priority to me. I think the changes above are good enough for now.

**Comment by thomasf** [comment]
I made it more violet to make it feel more as a unit.

![image](https://cloud.githubusercontent.com/assets/330847/13716659/c64a0778-e7dc-11e5-845b-ebeae41b8b63.png)

**Comment by oscarfv** [comment]
Thanks @thomasf but it seems that you omitted part of the change. The parens now are unbalanced on `magit-blame-summary`.

**Comment by thomasf** [comment]
Sorry, fixing it

**Comment by oscarfv** [comment]
It is fixed now, thank you @thomasf.

It doesn't look bad at all, although your idea about the line prefix might be helpful when the eye scans upwards for locating the `magit-blame` header that corresponds to the code line you are interested on.
