### ISSUE TITLE
Weird rendering of mode line

### ISSUE THREAD

**Issue by mrkkrp** [bbatsov/solarized-emacs#203]
I'm using `solarized-dark` on Arch Linux (xfce). Mode line doesn't look very good:

![solarized](https://cloud.githubusercontent.com/assets/8165792/9577323/241b2246-4ff9-11e5-8b2f-3389165894af.png)

Highlighting of modeline of active window is larger then necessary. Also consider making borders of modeline painted with the same color (currently top border is different from bottom one).

Other themes don't suffer from these quirks:

![monokai](https://cloud.githubusercontent.com/assets/8165792/9577356/7a750404-4ff9-11e5-9ab2-a55003d0e2a4.png)

**Comment by mrkkrp** [comment]
Comparing these two screenshots in browser (switching between tabs where one screenshot is opened per tab) I conclude that modeline highlighting is OK, but borders of modeline are shifted to the top a bit.

I guess you're using OS X and don't experience this, or else you would have fixed it already.

**Comment by thomasf** [comment]
I mainly use emacs on Ubuntu/XMonad with the lucid toolkit but also osx.

This is covered in the faq: https://github.com/bbatsov/solarized-emacs#underline-position-setting-for-x

**Comment by mrkkrp** [comment]
@thomasf, why do you need to have separately colored lines? Wouldn't it be much prettier if modeline were rendered like in the second screenshot?

**Comment by mrkkrp** [comment]
@thomasf, by the way `(setq x-underline-at-descent-line t)` solves the problem, although I don't understand why you need these complications. When top line is colored differently from the bottom line I personally don't see any benefit in it, only unnecessary complication.

**Comment by mrkkrp** [comment]
Since the problem is solved for me, I'm closing this. (I had to read FAQ before posting the issue, though.)

**Comment by thomasf** [comment]
The complications are because I want a low contrast theme for the mode line which preferably doesn't use any non solarized colors..

The interaction between multiple mode and header lines becomes a little tricky.

I think this screenshot is displaying a problematic view to get right without resorting to accent colors or non solarized colors (there is actually one non solarized color here, I've added one specifically to draw thinner lines with)

![image](https://cloud.githubusercontent.com/assets/330847/9642720/1e56fd82-51be-11e5-9ac9-d21466860128.png)
