### ISSUE TITLE
Question: what difference from other solarized theme

### ISSUE THREAD

**Issue by geraldus** [bbatsov/solarized-emacs#219]
Hi, Bozhidar! 

I'm curious what is the difference between your package and this one https://github.com/sellout/emacs-color-theme-solarized ?

**Comment by thomasf** [comment]
Many small and large differences.. You have to take a look and decide for yourself.

**Comment by geraldus** [comment]
Well, I can't do side by side comparison because if I install both themes they conflict.  I see much better package support, however comments are not italicized, I should play with customizations I guess.

**Comment by geraldus** [comment]
@thomasf ok, `solarized-use-more-italic` does not affect comments.  Looking at http://ethanschoonover.com/solarized I see that most screenshots have italicized comments, will you guys accept a PR for italicized comments?

**Comment by geraldus** [comment]
Also, `whitespace-newline-face` have same colouring as comment face (though this issues present also in sellout repository it is definitely should be different according to screenshots from http://ethanschoonover.com/solarized)

**Comment by thomasf** [comment]
It's intentional to generally be very restrictive about color use here, probably more so than other instances of solarized themes. Solarized is in it's basic form only a palette so theme implementations might differ from the screenshots of the solarized upstream web page in various ways.

I've written a draft guide for how this theme chooses colors here: https://github.com/bbatsov/solarized-emacs/blob/master/DEV-GUIDE.md  .. 

IIRC italicized comments was removed because it shadows some other display situation, I'm not sure though.

I don't have time to check the white space mode stuff.. In this theme ws mode has had a lot of integration issues with other modes because of the small number of colors available in total.

**Comment by thomasf** [comment]
A simple difference between this and th

**Comment by geraldus** [comment]
Ok, I took some screenshots.

In general colors vary very much.  Is this a bug or there is some reason for such variation?

This is screenshot of bbastov's theme
![2016-01-28 21 40 05](https://cloud.githubusercontent.com/assets/744471/12651417/4cea9488-c608-11e5-866d-cee9c74fd936.png)

This how same code looks in Neovim with Solarized from official repository
![2016-01-28 21 33 27](https://cloud.githubusercontent.com/assets/744471/12651436/58c5e4ec-c608-11e5-94e0-5e64eb972607.png)

This is how same code looks with Emacs sub-repository (sorry for different font)
![2016-01-28 9 36 45 pm](https://cloud.githubusercontent.com/assets/744471/12651457/69ec0e4a-c608-11e5-825b-071ba61f8679.png)

And this is screenshot for Haskell code from official site:
![screen](http://ethanschoonover.com/solarized/img/screen-haskell-light.png)

**Comment by thomasf** [comment]
They are just different themes.

There is no official solarized specification for how the solarized palette accent colors are supposed to be used and it would be an next to impossible task anyway since each application implementing the palette has specific needs for what to highlight.

See the development guide I linked earlier for a draft specification how this theme uses the colors.

**Comment by thomasf** [comment]
I've probably spend well over 100 hours simplifying the color usage in this theme, some times I've come to the conclusion to use the same look for different things instead of creating color pasta instead of clearly communicating the most important information which I feel is the case with the haskell screenshot from the official site.

**Comment by thomasf** [comment]
here's a screenshot of my xmonad config for reference, magenta is used by auto-highlight-symbol as a temporary highlight here as specified how magenta is used in  the dev guide.

![image](https://cloud.githubusercontent.com/assets/330847/12652725/6aad7f4c-c5ec-11e5-9a3c-a3e4dc2c4a45.png)

**Comment by geraldus** [comment]
Ok, got it.  But in this case the meaning of
> Solarized for Emacs is an Emacs port of the Solarized theme for vim, developed by Ethan Schoonover.

is unclear for me.  I'll take a closer look at Ethan's theme in Vim (I've not used it for very long time) and see how it works for other files.  Is it ok to ask questions in this topic?

**Comment by thomasf** [comment]
I was answering while eating dinner just now.. I'm super busy finishing another project in the next days so it's not clear to me if I will have time to reply or not but go ahead and ask.

And, we should probably update that statement in the readme.. This theme even goes against rule #1 (i think) in the upstream solarized dev guide which is to never add any other colors..

The auto-complete popup at the top and vc-annotate at the bottom uses non upstream solarized colors.. I try to avoid doing this but sometimes it really make sense to do it.

![image](https://cloud.githubusercontent.com/assets/330847/12653036/ef07fc8a-c5ed-11e5-919e-74435d6538a2.png)
