### ISSUE TITLE
provide a toggle-solarized-theme (or similar) function

### ISSUE THREAD

**Issue by wbolster** [bbatsov/solarized-emacs#221]
i would love to have simple way to toggle between dark and light modes (e.g. because light conditions changed). i currently work around this using a variable and a toggle function in my `init.el` like this:

``` elisp
(load-theme 'solarized-dark t)
(setq active-theme 'solarized-dark)
(defun toggle-dark-light-theme ()
  (interactive)
  (if (eq active-theme 'solarized-light)
      (setq active-theme 'solarized-dark)
    (setq active-theme 'solarized-light))
  (load-theme active-theme))
```

it would be nicer to have this functionality built-in.

**Comment by thomasf** [comment]
I don't think its something that should go in this theme.. It's more of a general feature that would probably be better as it's own package..

I have an even more involced version which also changes theme by looking for a
file named `darkmode` which I use to toggle dark/bright solarized for my xmonad
wm as well as emacs and open terminals:

```el
(defvar theme-bright nil "A light theme.")
(defvar theme-dark nil "A dark theme.")

(setq theme-dark 'my-solarized-dark
      theme-bright 'my-solarized-light)
          
(defun post-change-theme ()
  (set-face-inverse-video-p 'vertical-border nil)
  (set-face-background 'vertical-border (face-background 'default)))

(eval
 '(set-display-table-slot standard-display-table
                          'vertical-border
                          (make-glyph-code ? )))

(defun dark-theme ()
  "Switch to dark mode (dark color theme)."
  (interactive)
  (when theme-dark
    (load-theme theme-dark t)
    (setq dark-theme-on t)
    (post-change-theme)))

(defun bright-theme ()
  "Switch to light mode (light color theme)."
  (interactive)
  (when theme-bright
    (load-theme theme-bright t)
    (setq dark-theme-on nil)
    (post-change-theme)))

(defun toggle-dark-theme ()
  "Toggle between light and dark modes."
  (interactive)
  (if (bound-and-true-p dark-theme-on)
      (bright-theme)
    (dark-theme))
  (post-change-theme))

(and (not (boundp 'dark-theme-on))
     (not noninteractive)
     ;; (not (not window-system))
     (not degrade-p-minimalism)
     (if (file-exists-p "~/.config/darkmode")
         (dark-theme)
       (bright-theme)))

(add-hook 'focus-in-hook
          #'(lambda ()
              (if (file-exists-p "~/.config/darkmode")
                  (when (not dark-theme-on) (dark-theme))
                (when dark-theme-on (bright-theme)))))


```

**Comment by thomasf** [comment]
I also set theme-dark / theme-light to other values depending on the terminal being used.. For 256color terminals I actually use `zenburn`/`anti-zenburn` instead because I think they are better fitted for the 256c terminal palette.

**Comment by thomasf** [comment]
my desktop theming:

dark:

![image](https://cloud.githubusercontent.com/assets/330847/12951706/e2eccee6-d013-11e5-9810-c1c69b0cd8cd.png)

bright:

![image](https://cloud.githubusercontent.com/assets/330847/12951716/f024cbc2-d013-11e5-8372-61a5f1bc0c6f.png)

:)

**Comment by wbolster** [comment]
> i don't think its something that should go in this theme.. it's more of a general feature that would probably be better as it's own package..

i do not agree. this awesome theme explicitly provides a light and dark mode, so having a way to switch between those would be just fine inside this package.

(technically those are two themes sharing quite a lot of code, but that's an implementation detail.)

**Comment by wbolster** [comment]
can a maintainer tell me whether a `toggle-solarized-theme` command will be accepted for this project? if not, feel free to close this issue.

**Comment by malikcpp** [comment]
i agree with @wbolster, at least would a maintainer explain this possible feature implementation in the README (or simply link [this issue](https://github.com/bbatsov/solarized-emacs/issues/221)) for  non familiar emacs users with `load-theme` instead of [this](https://github.com/bbatsov/solarized-emacs/issues/221).

**Comment by bsima** [comment]
@wbolster This is a nice package that already does this based on time settings: https://github.com/guidoschmidt/circadian.el

Should be easy to add a "toggle" function (if it doesn't already exist in the package)

**Comment by malikbenkirane** [comment]
Yes I did it when I was still using emacs. I can find back there the method
I used for the people who had difficulty on this feature.

Although I became a neovim passionate since I still appreciate emacs lisp
beauty (and of all his cousins) and would love to find those scripts and
then share them. Just ask; for me I'll have a look on that package you
mention


On Oct 9, 2017 19:26, "Ben Sima" <notifications@github.com> wrote:

@wbolster <https://github.com/wbolster> This is a nice package that already
does this based on time settings: https://github.com/
guidoschmidt/circadian.el

Should be easy to add a "toggle" function (if it doesn't already exist in
the package)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/bbatsov/solarized-emacs/issues/221#issuecomment-335225083>,
or mute the thread

**Comment by adrianstaniec** [comment]
I use this package: https://github.com/valignatev/heaven-and-hell
like so:
```
(use-package heaven-and-hell
  :init
  (setq heaven-and-hell-theme-type 'dark)
  (setq heaven-and-hell-themes
        '((light . solarized-light)
          (dark . solarized-dark)))
  :hook (after-init . heaven-and-hell-init-hook)
  :bind (("C-c <f6>" . heaven-and-hell-load-default-theme)
         ("<f6>" . heaven-and-hell-toggle-theme)))
```
