### ISSUE TITLE
Review usage of orange/red/magenta 

### ISSUE THREAD

**Issue by thomasf** [bbatsov/solarized-emacs#98]
- Red/orange should be used for errors/warnings with possible rare exceptions.
- Magenta should mostly be used for temporary highlight, avoid other usage if possible.

**Comment by andersjohansson** [comment]
Great idea! I've always been redefining org/outline-heading colors since I find the orange too sharp. I've done it in a cycle of the four solarized colors I find most neutral (this was for sellouts theme, which had the same problem):
```elisp
(outline-1 (,@fmt-none ,@fg-blue))
(outline-2 (,@fmt-none ,@fg-cyan))
(outline-3 (,@fmt-none ,@fg-yellow))
(outline-4 (,@fmt-none ,@fg-green))
(outline-5 (,@fmt-none ,@fg-blue))
(outline-6 (,@fmt-none ,@fg-cyan))
(outline-7 (,@fmt-none ,@fg-yellow))
(outline-8 (,@fmt-none ,@fg-green))
```
I think doing something like this would be good, and perhaps people wouldn't be too confused.
